In [1]:
pip install pandas numpy matplotlib seaborn scikit-learn nltk wordcloud jupyter

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (2.0.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (1.24.4)
Requirement already satisfied: matplotlib in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (3.7.5)
Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (0.13.2)
Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp38-cp38-win_amd64.whl.metadata (11 kB)
Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting wordcloud
  Downloading wordcloud-1.9.4-cp38-cp38-win_amd64.whl.metadata (3.5 kB)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (3.1.4)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from matplotlib) (6.4.5)
Collecting scipy>=1.5.0 (from scikit-learn)
  Downloading scipy-1.10.1-cp38-cp38-win_amd64.whl.metadata (58 kB)
Requirement already satisfied: joblib>=1.1.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.4.2)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nltk) (8.1.8)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp38-cp38-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: notebook in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (7.3.3)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nbconvert in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (6.29.5)
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: jupyterlab in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (4.3.8)
Requirement already satisfied: zipp>=3.1.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.20.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (8.12.3)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=24 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-console->jupyter) (3.0.52)
Requirement already satisfied: pygments in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-console->jupyter) (2.19.2)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: importlib-metadata>=4.8.3 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (8.5.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (56.0.0)
Requirement already satisfied: tomli>=1.2.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab->jupyter) (2.4.1)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (2.1.5)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.10.1)
Requirement already satisfied: nbformat>=5.7 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from async-lru>=1.0.0->jupyterlab->jupyter) (4.13.2)
Requirement already satisfied: webencodings in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.3,>=1.1.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.2.1)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (4.5.2)
Requirement already satisfied: certifi in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (3.15)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: backcall in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: decorator in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: jedi>=0.16 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: pickleshare in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.7.5)
Requirement already satisfied: stack-data in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (311)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: overrides>=5.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.13)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.21.2)
Requirement already satisfied: wcwidth in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.8.2)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2023.12.1)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (1.3.10)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.20.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.2.3)
Requirement already satisfied: executing>=1.2.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (3.0.2)
Requirement already satisfied: pure-eval in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: fqdn in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("data/raw/amazon_reviews.csv")

In [4]:
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [5]:
df.shape

(23486, 11)

In [6]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [8]:
df.describe(include="all")

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
count,23486.000000,23486.000000,23486.000000,19676,22641,23486.000000,23486.000000,23486.000000,23472,23472,23472
unique,NaN,NaN,NaN,13993,22634,NaN,NaN,NaN,3,6,20
top,NaN,NaN,NaN,Love it!,Perfect fit and i've gotten so many compliment...,NaN,NaN,NaN,General,Tops,Dresses
freq,NaN,NaN,NaN,136,3,NaN,NaN,NaN,13850,10468,6319
mean,11742.500000,918.118709,43.198544,NaN,NaN,4.196032,0.822362,2.535936,NaN,NaN,NaN
std,6779.968547,203.298980,12.279544,NaN,NaN,1.110031,0.382216,5.702202,NaN,NaN,NaN
min,0.000000,0.000000,18.000000,NaN,NaN,1.000000,0.000000,0.000000,NaN,NaN,NaN
25%,5871.250000,861.000000,34.000000,NaN,NaN,4.000000,1.000000,0.000000,NaN,NaN,NaN
50%,11742.500000,936.000000,41.000000,NaN,NaN,5.000000,1.000000,1.000000,NaN,NaN,NaN
75%,17613.750000,1078.000000,52.000000,NaN,NaN,5.000000,1.000000,3.000000,NaN,NaN,NaN
max,23485.000000,1205.000000,99.000000,NaN,NaN,5.000000,1.000000,122.000000,NaN,NaN,NaN

In [9]:
df.sample(5)

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
14495,14495,909,49,Returned,"The fit was not flattering at all, but the wor...",1,0,0,General,Tops,Fine gauge
21539,21539,1094,28,Super cute but large,"As other reviewers have mentioned, this dress ...",4,1,0,General Petite,Dresses,Dresses
23112,23112,1083,41,Weird bulge in the back zipper?,I just scoured the other reviews to see if any...,4,1,1,General,Dresses,Dresses
14049,14049,864,56,Amazing,Perfect for work or a night out. packing for e...,5,1,0,General Petite,Tops,Knits
19099,19099,453,34,Please stop going down in fabric quality,"I've been wearing these shorts for years, i wo...",2,0,3,General,Bottoms,Shorts

# Day 1

## Objective
Understand the dataset and explore its structure.

### Tasks Completed
- Imported libraries
- Loaded dataset
- Viewed first few rows
- Checked dataset dimensions
- Examined columns and data types